# -*- coding: utf-8 -*-
# Agustin Wisky <agustinwisky@capitole-consulting.com> 
# CAPITOLE CONSULTING S.L.

version: '3'
services:
  web:
    image: odoo:11.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    tty: true
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
      - ./addons_oca:/mnt/oca-addons
  db:
    image: postgres:10
    env_file:
      - db.env
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
  proxy:
    depends_on:
        - web
    build:
        context: .
        dockerfile: Dockerfile-Nginx
    ports:
        - "80:80"
volumes:
  odoo-web-data:
  odoo-db-data:
